name: test
on: 
    push:
    workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          curl -X POST -u "${{ secrets.USERNAME}}:${{secrets.TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/gatomek/flashcards-mongodb-data-uploader/actions/workflows/test.yml/dispatches --data "{\"ref\": \"main\"}"
